### ISSUE TITLE
gcc-4.9 ou gcc-5 ?

### ISSUE THREAD

**Issue by VonUniGE** [EtiennePasteur/Lettrine#4]
Debian 8, qui est utilisé sur nos serveurs, ne dispose pas, à ma connaissance, de paquets pour gcc-5. Compilé avec gcc-4.9.2, le programme tourne sans problème mais `ctest` génère un SEGFAULT. Je ne suis pas un spécialiste C++ et je me demande quelle est la meilleure solution?

**Comment by EtiennePasteur** [comment]
La commande `ctest --verbose` permet juste de lancer des phases de tests afin de s'assurer que le programme extraie bien le bon nombre d'images. (les tests ne sont pas encore codés).

Tu n'es donc pas obligé de lancer cette commande.
Je vais essayer de compiler le projet sous Debian 8 avec gcc4.9.2 demain pour voir si j'arrive à reproduire l'erreur.

**Comment by EtiennePasteur** [comment]
J'ai réussi à reproduire l'erreur avec Debian8 et `gcc-4.9.2` et elle vient du framework de test que nous utilisons (GoogleTest). En passant sous `gcc-5` l'erreur disparaît mais j'ai dû ajouter les dépôts testing de Debian (ce que je ne recommande pas).

Je me permets de rajouter que la commande `ctest --verbose` n'est en rien essentielle au bon fonctionnement du programme, de plus les test sont effectués sur TravisCI automatiquement à chaque commit. (https://travis-ci.org/EtiennePasteur/Lettrine)
