### ISSUE TITLE
Permettre le traitement d'une seule image à la fois

### ISSUE THREAD

**Issue by VonUniGE** [EtiennePasteur/Lettrine#7]
Actuellement Lettrine assume une structure de dossier prédéterminée.

Il serait avantageux de permettre le traitement d'une seule image à la fois. Lettrine pourrait être ainsi utilisé dans des scripts qui se chargeraient de parcourir les dossiers. Lettrine se concentrerait sur le traitement d'images.

**Comment by EtiennePasteur** [comment]
Bonjour,

Le programme est désormais plus souple sur la structure des dossiers.
Il existe désormais 3 flags :
```sh
Lettrine -d <nom du dossier à scanner> #il va scanner toutes les images présentes dans le dossier.
Lettrine -f <nom du fichier> #il va scanner uniquement le fichier.
Lettrine -o <nom du dossier de destination> # (par défaut : extracted) nom du dossier des images extraites
```

**Comment by VonUniGE** [comment]
Bonjour,

Merci beaucoup, cela sera bien plus pratique comme cela.

Cordialement,

Mathieu Vonlanthen
